controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_login_check:
    path: /api/login_check

# route 'detailClient' pour pouvoir créer un nouveau client san serreur 500
detailClient:
    path: /clients/{id}
    controller: App\Controller\ClientController::getDetailClient
    methods: GET